id: qbiq
name: 260310-qbiq-go-wt-binary
created: 2026-03-10T13:45:21.981595+05:30
created_by: sahil-weaver
change_type: refactor
issues: []
progress:
  intake: done
  spec: done
  tasks: done
  apply: done
  review: done
  hydrate: done
  ship: done
  review-pr: active
checklist:
  generated: true
  path: checklist.md
  completed: 0
  total: 38
confidence:
  certain: 12
  confident: 1
  tentative: 0
  unresolved: 0
  score: 4.7
  fuzzy: true
  dimensions:
    signal: 91.9
    reversibility: 82.7
    competence: 85.0
    disambiguation: 84.2
stage_metrics:
  intake: {started_at: "2026-03-10T13:45:21.984131+05:30", driver: fab-new, iterations: 1, completed_at: "2026-03-10T10:17:08Z"}
  spec: {started_at: "2026-03-10T10:17:08Z", driver: fab-ff, iterations: 1, completed_at: "2026-03-10T10:19:39Z"}
  tasks: {started_at: "2026-03-10T10:19:39Z", driver: fab-ff, iterations: 1, completed_at: "2026-03-10T10:20:54Z"}
  apply: {started_at: "2026-03-10T10:36:38Z", driver: fab-ff, iterations: 2, completed_at: "2026-03-10T10:37:33Z"}
  review: {started_at: "2026-03-10T10:37:33Z", driver: fab-ff, iterations: 1, completed_at: "2026-03-10T10:37:50Z"}
  hydrate: {started_at: "2026-03-10T10:37:50Z", driver: fab-ff, iterations: 1, completed_at: "2026-03-10T10:42:56Z"}
  ship: {started_at: "2026-03-10T10:42:56Z", driver: fab-ff, iterations: 1, completed_at: "2026-03-10T10:45:01Z"}
  review-pr: {started_at: "2026-03-10T10:45:01Z", driver: git-pr, iterations: 1, phase: fixing, reviewer: 'copilot-pull-request-reviewer[bot]'}
prs:
  - https://github.com/wvrdz/fab-kit/pull/238
last_updated: 2026-03-10T10:45:01Z
